[package]
name = "mre_tree"
version = "0.1.0"
edition = "2021"

[dependencies]
cairo-vm = { git = "https://github.com/Moonsong-Labs/cairo-vm", branch = "notlesh/snos-2024-11-04", features = ["cairo-1-hints", "extensive_hints", "mod_builtin"] }
